name: Container Builds
on:
  push:
    branches: [ master ]
jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build the key submission image
      run: docker build --build-arg component=key-submission -t key-submission:${{ github.sha }} .

    - uses: Azure/container-scan@v0
      with:
        image-name: key-submission:${{ github.sha }}

    - name: Push key-submission Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: key-submission
      run: |
        docker tag key-submission:${{ github.sha }} $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker tag key-submission:${{ github.sha }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
        docker push $ECR_REGISTRY/key-submission:${{ github.sha }}
        docker push $ECR_REGISTRY/key-submission:latest

    - name: Build the key retrieval image
      run: docker build --build-arg component=key-retrieval -t key-retrieval:${{ github.sha }} .

    - uses: Azure/container-scan@v0
      with:
        image-name: key-retrieval:${{ github.sha }}

    - name: Push key-retrieval Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: key-retrieval
      run: |
        docker tag key-retrieval:${{ github.sha }} $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker tag key-retrieval:${{ github.sha }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
        docker push $ECR_REGISTRY/key-retrieval:${{ github.sha }}
        docker push $ECR_REGISTRY/key-retrieval:latest

    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
