name: Docker CI
on: [pull_request]
jobs:
  key-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker build --build-arg component=${{ github.job }} -t ${{ github.job }}:${{ github.sha }} .
    - name: Hadolint
      uses: Shopify/gh-action-hadolint@master
    - uses: Azure/container-scan@v0
      with:
        image-name: ${{ github.job }}:${{ github.sha }}

  key-retrieval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker build --build-arg component=${{ github.job }} -t ${{ github.job }}:${{ github.sha }} .
    - name: Hadolint
      uses: Shopify/gh-action-hadolint@master
    - uses: Azure/container-scan@v0
      with:
        image-name: ${{ github.job }}:${{ github.sha }}
